// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfojwyukfymfvgvhvyvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmb2p3eXVrZnltZnZndmh2eXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTEzNTksImV4cCI6MjA2NzQ4NzM1OX0.O0Nk-qZSGjwGGSwC17f5Q-wxaWDg3ZR6Bq9CJ__kI0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});